// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: agent.proto

package agentinnerservice

import (
	"context"

	"github.com/QuantumShiftX/farms-proto/proto-gen-go/agent/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AgentReply                 = v1.AgentReply
	AgentReq                   = v1.AgentReq
	DownlineMember             = v1.DownlineMember
	GetAgentDownlineListReq    = v1.GetAgentDownlineListReq
	GetAgentDownlineListResp   = v1.GetAgentDownlineListResp
	GetAgentDownlineStatsReq   = v1.GetAgentDownlineStatsReq
	GetAgentDownlineStatsResp  = v1.GetAgentDownlineStatsResp
	GetAgentIncomeDetailsReq   = v1.GetAgentIncomeDetailsReq
	GetAgentIncomeDetailsResp  = v1.GetAgentIncomeDetailsResp
	GetAgentIncomeOverviewReq  = v1.GetAgentIncomeOverviewReq
	GetAgentIncomeOverviewResp = v1.GetAgentIncomeOverviewResp
	IncomeDetail               = v1.IncomeDetail

	AgentInnerService interface {
		// 获取代理收入概览
		GetAgentIncomeOverview(ctx context.Context, in *GetAgentIncomeOverviewReq, opts ...grpc.CallOption) (*GetAgentIncomeOverviewResp, error)
		// 获取代理下线统计
		GetAgentDownlineStats(ctx context.Context, in *GetAgentDownlineStatsReq, opts ...grpc.CallOption) (*GetAgentDownlineStatsResp, error)
		// 获取代理下线列表
		GetAgentDownlineList(ctx context.Context, in *GetAgentDownlineListReq, opts ...grpc.CallOption) (*GetAgentDownlineListResp, error)
		// 获取代理收入明细
		GetAgentIncomeDetails(ctx context.Context, in *GetAgentIncomeDetailsReq, opts ...grpc.CallOption) (*GetAgentIncomeDetailsResp, error)
	}

	defaultAgentInnerService struct {
		cli zrpc.Client
	}
)

func NewAgentInnerService(cli zrpc.Client) AgentInnerService {
	return &defaultAgentInnerService{
		cli: cli,
	}
}

// 获取代理收入概览
func (m *defaultAgentInnerService) GetAgentIncomeOverview(ctx context.Context, in *GetAgentIncomeOverviewReq, opts ...grpc.CallOption) (*GetAgentIncomeOverviewResp, error) {
	client := v1.NewAgentInnerServiceClient(m.cli.Conn())
	return client.GetAgentIncomeOverview(ctx, in, opts...)
}

// 获取代理下线统计
func (m *defaultAgentInnerService) GetAgentDownlineStats(ctx context.Context, in *GetAgentDownlineStatsReq, opts ...grpc.CallOption) (*GetAgentDownlineStatsResp, error) {
	client := v1.NewAgentInnerServiceClient(m.cli.Conn())
	return client.GetAgentDownlineStats(ctx, in, opts...)
}

// 获取代理下线列表
func (m *defaultAgentInnerService) GetAgentDownlineList(ctx context.Context, in *GetAgentDownlineListReq, opts ...grpc.CallOption) (*GetAgentDownlineListResp, error) {
	client := v1.NewAgentInnerServiceClient(m.cli.Conn())
	return client.GetAgentDownlineList(ctx, in, opts...)
}

// 获取代理收入明细
func (m *defaultAgentInnerService) GetAgentIncomeDetails(ctx context.Context, in *GetAgentIncomeDetailsReq, opts ...grpc.CallOption) (*GetAgentIncomeDetailsResp, error) {
	client := v1.NewAgentInnerServiceClient(m.cli.Conn())
	return client.GetAgentIncomeDetails(ctx, in, opts...)
}
