// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: agent.proto

package agentinnerservice

import (
	"context"

	"github.com/QuantumShiftX/farms-proto/proto-gen-go/agent/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AgentReply                     = v1.AgentReply
	AgentReq                       = v1.AgentReq
	DownlineMember                 = v1.DownlineMember
	GetAgentDownlineListMsgReply   = v1.GetAgentDownlineListMsgReply
	GetAgentDownlineListMsgReq     = v1.GetAgentDownlineListMsgReq
	GetAgentDownlineStatsMsgReply  = v1.GetAgentDownlineStatsMsgReply
	GetAgentDownlineStatsMsgReq    = v1.GetAgentDownlineStatsMsgReq
	GetAgentIncomeDetailsMsgReply  = v1.GetAgentIncomeDetailsMsgReply
	GetAgentIncomeDetailsMsgReq    = v1.GetAgentIncomeDetailsMsgReq
	GetAgentIncomeOverviewMsgReply = v1.GetAgentIncomeOverviewMsgReply
	GetAgentIncomeOverviewMsgReq   = v1.GetAgentIncomeOverviewMsgReq
	IncomeDetail                   = v1.IncomeDetail

	AgentInnerService interface {
		// 获取代理收入概览
		GetAgentIncomeOverview(ctx context.Context, in *GetAgentIncomeOverviewMsgReq, opts ...grpc.CallOption) (*GetAgentIncomeOverviewMsgReply, error)
		// 获取代理下线统计
		GetAgentDownlineStats(ctx context.Context, in *GetAgentDownlineStatsMsgReq, opts ...grpc.CallOption) (*GetAgentDownlineStatsMsgReply, error)
		// 获取代理下线列表
		GetAgentDownlineList(ctx context.Context, in *GetAgentDownlineListMsgReq, opts ...grpc.CallOption) (*GetAgentDownlineListMsgReply, error)
		// 获取代理收入明细
		GetAgentIncomeDetails(ctx context.Context, in *GetAgentIncomeDetailsMsgReq, opts ...grpc.CallOption) (*GetAgentIncomeDetailsMsgReply, error)
	}

	defaultAgentInnerService struct {
		cli zrpc.Client
	}
)

func NewAgentInnerService(cli zrpc.Client) AgentInnerService {
	return &defaultAgentInnerService{
		cli: cli,
	}
}

// 获取代理收入概览
func (m *defaultAgentInnerService) GetAgentIncomeOverview(ctx context.Context, in *GetAgentIncomeOverviewMsgReq, opts ...grpc.CallOption) (*GetAgentIncomeOverviewMsgReply, error) {
	client := v1.NewAgentInnerServiceClient(m.cli.Conn())
	return client.GetAgentIncomeOverview(ctx, in, opts...)
}

// 获取代理下线统计
func (m *defaultAgentInnerService) GetAgentDownlineStats(ctx context.Context, in *GetAgentDownlineStatsMsgReq, opts ...grpc.CallOption) (*GetAgentDownlineStatsMsgReply, error) {
	client := v1.NewAgentInnerServiceClient(m.cli.Conn())
	return client.GetAgentDownlineStats(ctx, in, opts...)
}

// 获取代理下线列表
func (m *defaultAgentInnerService) GetAgentDownlineList(ctx context.Context, in *GetAgentDownlineListMsgReq, opts ...grpc.CallOption) (*GetAgentDownlineListMsgReply, error) {
	client := v1.NewAgentInnerServiceClient(m.cli.Conn())
	return client.GetAgentDownlineList(ctx, in, opts...)
}

// 获取代理收入明细
func (m *defaultAgentInnerService) GetAgentIncomeDetails(ctx context.Context, in *GetAgentIncomeDetailsMsgReq, opts ...grpc.CallOption) (*GetAgentIncomeDetailsMsgReply, error) {
	client := v1.NewAgentInnerServiceClient(m.cli.Conn())
	return client.GetAgentIncomeDetails(ctx, in, opts...)
}
