// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: user.proto

package userplantgrowthservice

import (
	"context"

	"github.com/QuantumShiftX/farms-proto/proto-gen-go/user/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdjustHarvestTimeRequest        = v1.AdjustHarvestTimeRequest
	AdjustHarvestTimeResponse       = v1.AdjustHarvestTimeResponse
	AllUserRankingInfoMsgReply      = v1.AllUserRankingInfoMsgReply
	AllUserRankingInfoMsgReq        = v1.AllUserRankingInfoMsgReq
	CheckCropsNeedsRequest          = v1.CheckCropsNeedsRequest
	CheckCropsNeedsResponse         = v1.CheckCropsNeedsResponse
	ForgotPasswordReq               = v1.ForgotPasswordReq
	FriendRankingInfo               = v1.FriendRankingInfo
	GetOnlineUserListReply          = v1.GetOnlineUserListReply
	GetOnlineUserListReq            = v1.GetOnlineUserListReq
	GrowthProgressRequest           = v1.GrowthProgressRequest
	GrowthProgressResponse          = v1.GrowthProgressResponse
	LookUserFarmsInfoMsgReply       = v1.LookUserFarmsInfoMsgReply
	LookUserFarmsInfoMsgReq         = v1.LookUserFarmsInfoMsgReq
	MaintenanceNeeds                = v1.MaintenanceNeeds
	MaintenanceNeedsRequest         = v1.MaintenanceNeedsRequest
	MaintenanceNeedsResponse        = v1.MaintenanceNeedsResponse
	MsgData                         = v1.MsgData
	MsgReply                        = v1.MsgReply
	MsgReq                          = v1.MsgReq
	MyRankingInfo                   = v1.MyRankingInfo
	PlantInfo                       = v1.PlantInfo
	PlantStateInfo                  = v1.PlantStateInfo
	PlantStateRequest               = v1.PlantStateRequest
	PlantStateResponse              = v1.PlantStateResponse
	PlantStatusRequest              = v1.PlantStatusRequest
	PlantStatusResponse             = v1.PlantStatusResponse
	RequestClientInfo               = v1.RequestClientInfo
	StageTime                       = v1.StageTime
	StageTimelinesRequest           = v1.StageTimelinesRequest
	StageTimelinesResponse          = v1.StageTimelinesResponse
	TimeReductionRequest            = v1.TimeReductionRequest
	TimeReductionResponse           = v1.TimeReductionResponse
	UserAuthInfoMsgReply            = v1.UserAuthInfoMsgReply
	UserAuthInfoMsgReq              = v1.UserAuthInfoMsgReq
	UserAuthenticationReply         = v1.UserAuthenticationReply
	UserAuthenticationReq           = v1.UserAuthenticationReq
	UserBalance                     = v1.UserBalance
	UserEditPersonalInfoMsgReply    = v1.UserEditPersonalInfoMsgReply
	UserEditPersonalInfoMsgReq      = v1.UserEditPersonalInfoMsgReq
	UserEditSensitiveInfoMsgReply   = v1.UserEditSensitiveInfoMsgReply
	UserEditSensitiveInfoMsgReq     = v1.UserEditSensitiveInfoMsgReq
	UserFarmInfoMsgReply            = v1.UserFarmInfoMsgReply
	UserFarmInfoMsgReq              = v1.UserFarmInfoMsgReq
	UserFarmOpsMsgReply             = v1.UserFarmOpsMsgReply
	UserFarmOpsMsgReq               = v1.UserFarmOpsMsgReq
	UserFortuneTreeInfo             = v1.UserFortuneTreeInfo
	UserFortuneTreeInfoMsgReply     = v1.UserFortuneTreeInfoMsgReply
	UserFortuneTreeInfoMsgReq       = v1.UserFortuneTreeInfoMsgReq
	UserFriendRankingInfoMsgReply   = v1.UserFriendRankingInfoMsgReply
	UserFriendRankingInfoMsgReq     = v1.UserFriendRankingInfoMsgReq
	UserIdReq                       = v1.UserIdReq
	UserLandDetail                  = v1.UserLandDetail
	UserLandInfoMsgReply            = v1.UserLandInfoMsgReply
	UserLandInfoMsgReq              = v1.UserLandInfoMsgReq
	UserLoginResp                   = v1.UserLoginResp
	UserOpsFortuneTreeMsgReply      = v1.UserOpsFortuneTreeMsgReply
	UserOpsFortuneTreeMsgReq        = v1.UserOpsFortuneTreeMsgReq
	UserPersonalInfoMsgReply        = v1.UserPersonalInfoMsgReply
	UserPersonalInfoMsgReq          = v1.UserPersonalInfoMsgReq
	UserPlantingDetail              = v1.UserPlantingDetail
	UserPurchaseGoodsMsgReply       = v1.UserPurchaseGoodsMsgReply
	UserPurchaseGoodsMsgReq         = v1.UserPurchaseGoodsMsgReq
	UserRegisterReq                 = v1.UserRegisterReq
	UserReply                       = v1.UserReply
	UserReq                         = v1.UserReq
	UserSignInReq                   = v1.UserSignInReq
	UserSignOutReq                  = v1.UserSignOutReq
	UserStorageDetail               = v1.UserStorageDetail
	UserStorageInfoMsgReply         = v1.UserStorageInfoMsgReply
	UserStorageInfoMsgReq           = v1.UserStorageInfoMsgReq
	UserWallet                      = v1.UserWallet
	VerifyAccountReq                = v1.VerifyAccountReq
	VerifySecondaryPasswordMsgReply = v1.VerifySecondaryPasswordMsgReply
	VerifySecondaryPasswordMsgReq   = v1.VerifySecondaryPasswordMsgReq

	UserPlantGrowthService interface {
		// 计算植物当前生长阶段
		CalculatePlantStatus(ctx context.Context, in *PlantStatusRequest, opts ...grpc.CallOption) (*PlantStatusResponse, error)
		// 计算操作减少的时间
		CalculateTimeReduction(ctx context.Context, in *TimeReductionRequest, opts ...grpc.CallOption) (*TimeReductionResponse, error)
		// 计算所有生长阶段时间点
		CalculateStageTimelines(ctx context.Context, in *StageTimelinesRequest, opts ...grpc.CallOption) (*StageTimelinesResponse, error)
		// 调整收获时间
		AdjustHarvestTime(ctx context.Context, in *AdjustHarvestTimeRequest, opts ...grpc.CallOption) (*AdjustHarvestTimeResponse, error)
		// 检查是否需要浇水/施肥
		CheckMaintenanceNeeds(ctx context.Context, in *MaintenanceNeedsRequest, opts ...grpc.CallOption) (*MaintenanceNeedsResponse, error)
		// 检查是否需要浇水/施肥
		CheckMaintenanceNeedsMap(ctx context.Context, in *CheckCropsNeedsRequest, opts ...grpc.CallOption) (*CheckCropsNeedsResponse, error)
		// 获取植物当前生长进度
		GetGrowthProgress(ctx context.Context, in *GrowthProgressRequest, opts ...grpc.CallOption) (*GrowthProgressResponse, error)
		// 获取植物当前状态的综合信息
		GetPlantCurrentState(ctx context.Context, in *PlantStateRequest, opts ...grpc.CallOption) (*PlantStateResponse, error)
	}

	defaultUserPlantGrowthService struct {
		cli zrpc.Client
	}
)

func NewUserPlantGrowthService(cli zrpc.Client) UserPlantGrowthService {
	return &defaultUserPlantGrowthService{
		cli: cli,
	}
}

// 计算植物当前生长阶段
func (m *defaultUserPlantGrowthService) CalculatePlantStatus(ctx context.Context, in *PlantStatusRequest, opts ...grpc.CallOption) (*PlantStatusResponse, error) {
	client := v1.NewUserPlantGrowthServiceClient(m.cli.Conn())
	return client.CalculatePlantStatus(ctx, in, opts...)
}

// 计算操作减少的时间
func (m *defaultUserPlantGrowthService) CalculateTimeReduction(ctx context.Context, in *TimeReductionRequest, opts ...grpc.CallOption) (*TimeReductionResponse, error) {
	client := v1.NewUserPlantGrowthServiceClient(m.cli.Conn())
	return client.CalculateTimeReduction(ctx, in, opts...)
}

// 计算所有生长阶段时间点
func (m *defaultUserPlantGrowthService) CalculateStageTimelines(ctx context.Context, in *StageTimelinesRequest, opts ...grpc.CallOption) (*StageTimelinesResponse, error) {
	client := v1.NewUserPlantGrowthServiceClient(m.cli.Conn())
	return client.CalculateStageTimelines(ctx, in, opts...)
}

// 调整收获时间
func (m *defaultUserPlantGrowthService) AdjustHarvestTime(ctx context.Context, in *AdjustHarvestTimeRequest, opts ...grpc.CallOption) (*AdjustHarvestTimeResponse, error) {
	client := v1.NewUserPlantGrowthServiceClient(m.cli.Conn())
	return client.AdjustHarvestTime(ctx, in, opts...)
}

// 检查是否需要浇水/施肥
func (m *defaultUserPlantGrowthService) CheckMaintenanceNeeds(ctx context.Context, in *MaintenanceNeedsRequest, opts ...grpc.CallOption) (*MaintenanceNeedsResponse, error) {
	client := v1.NewUserPlantGrowthServiceClient(m.cli.Conn())
	return client.CheckMaintenanceNeeds(ctx, in, opts...)
}

// 检查是否需要浇水/施肥
func (m *defaultUserPlantGrowthService) CheckMaintenanceNeedsMap(ctx context.Context, in *CheckCropsNeedsRequest, opts ...grpc.CallOption) (*CheckCropsNeedsResponse, error) {
	client := v1.NewUserPlantGrowthServiceClient(m.cli.Conn())
	return client.CheckMaintenanceNeedsMap(ctx, in, opts...)
}

// 获取植物当前生长进度
func (m *defaultUserPlantGrowthService) GetGrowthProgress(ctx context.Context, in *GrowthProgressRequest, opts ...grpc.CallOption) (*GrowthProgressResponse, error) {
	client := v1.NewUserPlantGrowthServiceClient(m.cli.Conn())
	return client.GetGrowthProgress(ctx, in, opts...)
}

// 获取植物当前状态的综合信息
func (m *defaultUserPlantGrowthService) GetPlantCurrentState(ctx context.Context, in *PlantStateRequest, opts ...grpc.CallOption) (*PlantStateResponse, error) {
	client := v1.NewUserPlantGrowthServiceClient(m.cli.Conn())
	return client.GetPlantCurrentState(ctx, in, opts...)
}
