// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: payment.proto

package userpaymentinnerservice

import (
	"context"

	"github.com/QuantumShiftX/farms-proto/proto-gen-go/payment/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AgentPayNotifyRequest            = v1.AgentPayNotifyRequest
	AgentPayNotifyResponse           = v1.AgentPayNotifyResponse
	ApplyAgentPayRequest             = v1.ApplyAgentPayRequest
	ApplyAgentPayResponse            = v1.ApplyAgentPayResponse
	CommonRequest                    = v1.CommonRequest
	CreateCashierRequest             = v1.CreateCashierRequest
	CreateCashierResponse            = v1.CreateCashierResponse
	CreateOrderRequest               = v1.CreateOrderRequest
	CreateOrderResponse              = v1.CreateOrderResponse
	PayNotifyData                    = v1.PayNotifyData
	PayNotifyResponse                = v1.PayNotifyResponse
	PayParams                        = v1.PayParams
	PaymentNotificationReq           = v1.PaymentNotificationReq
	PaymentReply                     = v1.PaymentReply
	PaymentReq                       = v1.PaymentReq
	QueryAgentPayBalanceRequest      = v1.QueryAgentPayBalanceRequest
	QueryAgentPayBalanceResponse     = v1.QueryAgentPayBalanceResponse
	QueryAgentPayCertificateRequest  = v1.QueryAgentPayCertificateRequest
	QueryAgentPayCertificateResponse = v1.QueryAgentPayCertificateResponse
	QueryAgentPayOrderRequest        = v1.QueryAgentPayOrderRequest
	QueryAgentPayOrderResponse       = v1.QueryAgentPayOrderResponse
	QueryOrderByUTRRequest           = v1.QueryOrderByUTRRequest
	QueryOrderRequest                = v1.QueryOrderRequest
	QueryOrderResponse               = v1.QueryOrderResponse
	RechargeChannel                  = v1.RechargeChannel
	RechargeChannelsMsgReply         = v1.RechargeChannelsMsgReply
	RechargeChannelsMsgReq           = v1.RechargeChannelsMsgReq
	UserRechargeMsgReply             = v1.UserRechargeMsgReply
	UserRechargeMsgReq               = v1.UserRechargeMsgReq
	UserWithdrawMsgReply             = v1.UserWithdrawMsgReply
	UserWithdrawMsgReq               = v1.UserWithdrawMsgReq

	UserPaymentInnerService interface {
		// 用户充值
		UserRecharge(ctx context.Context, in *UserRechargeMsgReq, opts ...grpc.CallOption) (*UserRechargeMsgReply, error)
		// 用户提现
		UserWithdraw(ctx context.Context, in *UserWithdrawMsgReq, opts ...grpc.CallOption) (*UserWithdrawMsgReply, error)
		// 接收支付通知
		ReceivePaymentNotice(ctx context.Context, in *PaymentNotificationReq, opts ...grpc.CallOption) (*PaymentReply, error)
		// 充值通道列表响应
		UserRechargeChannel(ctx context.Context, in *RechargeChannelsMsgReq, opts ...grpc.CallOption) (*RechargeChannelsMsgReply, error)
	}

	defaultUserPaymentInnerService struct {
		cli zrpc.Client
	}
)

func NewUserPaymentInnerService(cli zrpc.Client) UserPaymentInnerService {
	return &defaultUserPaymentInnerService{
		cli: cli,
	}
}

// 用户充值
func (m *defaultUserPaymentInnerService) UserRecharge(ctx context.Context, in *UserRechargeMsgReq, opts ...grpc.CallOption) (*UserRechargeMsgReply, error) {
	client := v1.NewUserPaymentInnerServiceClient(m.cli.Conn())
	return client.UserRecharge(ctx, in, opts...)
}

// 用户提现
func (m *defaultUserPaymentInnerService) UserWithdraw(ctx context.Context, in *UserWithdrawMsgReq, opts ...grpc.CallOption) (*UserWithdrawMsgReply, error) {
	client := v1.NewUserPaymentInnerServiceClient(m.cli.Conn())
	return client.UserWithdraw(ctx, in, opts...)
}

// 接收支付通知
func (m *defaultUserPaymentInnerService) ReceivePaymentNotice(ctx context.Context, in *PaymentNotificationReq, opts ...grpc.CallOption) (*PaymentReply, error) {
	client := v1.NewUserPaymentInnerServiceClient(m.cli.Conn())
	return client.ReceivePaymentNotice(ctx, in, opts...)
}

// 充值通道列表响应
func (m *defaultUserPaymentInnerService) UserRechargeChannel(ctx context.Context, in *RechargeChannelsMsgReq, opts ...grpc.CallOption) (*RechargeChannelsMsgReply, error) {
	client := v1.NewUserPaymentInnerServiceClient(m.cli.Conn())
	return client.UserRechargeChannel(ctx, in, opts...)
}
