// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: manage.proto

package manageinnerservice

import (
	"context"

	"github.com/QuantumShiftX/farms-proto/proto-gen-go/manage/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CollectionRewards    = v1.CollectionRewards
	DefaultVipInfoReply  = v1.DefaultVipInfoReply
	DepositRewards       = v1.DepositRewards
	ManageReply          = v1.ManageReply
	ManageReq            = v1.ManageReq
	RegistrationRewards  = v1.RegistrationRewards
	SendCaptchaReq       = v1.SendCaptchaReq
	SettingBaseInfoReply = v1.SettingBaseInfoReply
	SettlementConfig     = v1.SettlementConfig
	VipLevelDetail       = v1.VipLevelDetail

	ManageInnerService interface {
		GetDefaultVipInfo(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*DefaultVipInfoReply, error)
		GetSettingBaseInfo(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*SettingBaseInfoReply, error)
	}

	defaultManageInnerService struct {
		cli zrpc.Client
	}
)

func NewManageInnerService(cli zrpc.Client) ManageInnerService {
	return &defaultManageInnerService{
		cli: cli,
	}
}

func (m *defaultManageInnerService) GetDefaultVipInfo(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*DefaultVipInfoReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.GetDefaultVipInfo(ctx, in, opts...)
}

func (m *defaultManageInnerService) GetSettingBaseInfo(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*SettingBaseInfoReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.GetSettingBaseInfo(ctx, in, opts...)
}
