// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: manage.proto

package manageinnerservice

import (
	"context"

	"github.com/QuantumShiftX/farms-proto/proto-gen-go/manage/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AgentRuleInfoMsgReply         = v1.AgentRuleInfoMsgReply
	AgentRuleInfoMsgReq           = v1.AgentRuleInfoMsgReq
	AnnouncementsInfo             = v1.AnnouncementsInfo
	CollectionRewards             = v1.CollectionRewards
	CurrencyInfo                  = v1.CurrencyInfo
	CurrencyInfoMsgReq            = v1.CurrencyInfoMsgReq
	CurrencyInfoMsgReqReply       = v1.CurrencyInfoMsgReqReply
	CustomerService               = v1.CustomerService
	DefaultVipInfoReply           = v1.DefaultVipInfoReply
	DepositRewards                = v1.DepositRewards
	DesignatedVipInfoReply        = v1.DesignatedVipInfoReply
	ExchangeRateSettingInfoReply  = v1.ExchangeRateSettingInfoReply
	FaqCategoryItem               = v1.FaqCategoryItem
	FaqItem                       = v1.FaqItem
	FarmAgreementInfoMsgReply     = v1.FarmAgreementInfoMsgReply
	FarmAgreementInfoMsgReq       = v1.FarmAgreementInfoMsgReq
	GetApkAddressReply            = v1.GetApkAddressReply
	GetCustomerServiceReply       = v1.GetCustomerServiceReply
	GetCustomerServiceReq         = v1.GetCustomerServiceReq
	GetDesignatedVipInfoReq       = v1.GetDesignatedVipInfoReq
	GetDownloadAddrReply          = v1.GetDownloadAddrReply
	GetNotificationsListReply     = v1.GetNotificationsListReply
	GetNotificationsListReq       = v1.GetNotificationsListReq
	GetRateInfoMsgReply           = v1.GetRateInfoMsgReply
	GetRateInfoMsgReq             = v1.GetRateInfoMsgReq
	GetSystemConfReply            = v1.GetSystemConfReply
	ManageReply                   = v1.ManageReply
	ManageReq                     = v1.ManageReq
	NotificationInfo              = v1.NotificationInfo
	RegistrationRewards           = v1.RegistrationRewards
	SendCaptchaReq                = v1.SendCaptchaReq
	SettingBaseInfoReply          = v1.SettingBaseInfoReply
	SettlementConfig              = v1.SettlementConfig
	UserAnnouncementsInfoMsgReply = v1.UserAnnouncementsInfoMsgReply
	UserAnnouncementsInfoMsgReq   = v1.UserAnnouncementsInfoMsgReq
	VIPLevelInfo                  = v1.VIPLevelInfo
	VipLevelDetail                = v1.VipLevelDetail
	VipLevelInfoMsgReply          = v1.VipLevelInfoMsgReply
	VipLevelInfoMsgReq            = v1.VipLevelInfoMsgReq

	ManageInnerService interface {
		// 获取默认VIP等级信息
		GetDefaultVipInfo(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*DefaultVipInfoReply, error)
		// 获取指定VIP等级信息
		GetDesignatedVipInfo(ctx context.Context, in *GetDesignatedVipInfoReq, opts ...grpc.CallOption) (*DesignatedVipInfoReply, error)
		// 获取设置基础信息
		GetSettingBaseInfo(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*SettingBaseInfoReply, error)
		// 获取汇率设置
		GetExchangeRateSettingInfo(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*ExchangeRateSettingInfoReply, error)
		// 获取vip等级信息
		VipLevelInfo(ctx context.Context, in *VipLevelInfoMsgReq, opts ...grpc.CallOption) (*VipLevelInfoMsgReply, error)
		// 获取模板信息列表
		GetNotificationsList(ctx context.Context, in *GetNotificationsListReq, opts ...grpc.CallOption) (*GetNotificationsListReply, error)
		// 获取下载地址----addr
		GetDownloadAddress(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*GetDownloadAddrReply, error)
		// 获取公告
		UserAnnouncements(ctx context.Context, in *UserAnnouncementsInfoMsgReq, opts ...grpc.CallOption) (*UserAnnouncementsInfoMsgReply, error)
		// 获取协议
		GetFarmAgreement(ctx context.Context, in *FarmAgreementInfoMsgReq, opts ...grpc.CallOption) (*FarmAgreementInfoMsgReply, error)
		// 获取货币列表
		GetCurrencyInfoMsg(ctx context.Context, in *CurrencyInfoMsgReq, opts ...grpc.CallOption) (*CurrencyInfoMsgReqReply, error)
		// 获取代理规则信息
		GetAgentRuleInfoMsg(ctx context.Context, in *AgentRuleInfoMsgReq, opts ...grpc.CallOption) (*AgentRuleInfoMsgReply, error)
		// 获取当前汇率
		GetCurrentRateInfoMsg(ctx context.Context, in *GetRateInfoMsgReq, opts ...grpc.CallOption) (*GetRateInfoMsgReply, error)
	}

	defaultManageInnerService struct {
		cli zrpc.Client
	}
)

func NewManageInnerService(cli zrpc.Client) ManageInnerService {
	return &defaultManageInnerService{
		cli: cli,
	}
}

// 获取默认VIP等级信息
func (m *defaultManageInnerService) GetDefaultVipInfo(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*DefaultVipInfoReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.GetDefaultVipInfo(ctx, in, opts...)
}

// 获取指定VIP等级信息
func (m *defaultManageInnerService) GetDesignatedVipInfo(ctx context.Context, in *GetDesignatedVipInfoReq, opts ...grpc.CallOption) (*DesignatedVipInfoReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.GetDesignatedVipInfo(ctx, in, opts...)
}

// 获取设置基础信息
func (m *defaultManageInnerService) GetSettingBaseInfo(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*SettingBaseInfoReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.GetSettingBaseInfo(ctx, in, opts...)
}

// 获取汇率设置
func (m *defaultManageInnerService) GetExchangeRateSettingInfo(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*ExchangeRateSettingInfoReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.GetExchangeRateSettingInfo(ctx, in, opts...)
}

// 获取vip等级信息
func (m *defaultManageInnerService) VipLevelInfo(ctx context.Context, in *VipLevelInfoMsgReq, opts ...grpc.CallOption) (*VipLevelInfoMsgReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.VipLevelInfo(ctx, in, opts...)
}

// 获取模板信息列表
func (m *defaultManageInnerService) GetNotificationsList(ctx context.Context, in *GetNotificationsListReq, opts ...grpc.CallOption) (*GetNotificationsListReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.GetNotificationsList(ctx, in, opts...)
}

// 获取下载地址----addr
func (m *defaultManageInnerService) GetDownloadAddress(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*GetDownloadAddrReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.GetDownloadAddress(ctx, in, opts...)
}

// 获取公告
func (m *defaultManageInnerService) UserAnnouncements(ctx context.Context, in *UserAnnouncementsInfoMsgReq, opts ...grpc.CallOption) (*UserAnnouncementsInfoMsgReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.UserAnnouncements(ctx, in, opts...)
}

// 获取协议
func (m *defaultManageInnerService) GetFarmAgreement(ctx context.Context, in *FarmAgreementInfoMsgReq, opts ...grpc.CallOption) (*FarmAgreementInfoMsgReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.GetFarmAgreement(ctx, in, opts...)
}

// 获取货币列表
func (m *defaultManageInnerService) GetCurrencyInfoMsg(ctx context.Context, in *CurrencyInfoMsgReq, opts ...grpc.CallOption) (*CurrencyInfoMsgReqReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.GetCurrencyInfoMsg(ctx, in, opts...)
}

// 获取代理规则信息
func (m *defaultManageInnerService) GetAgentRuleInfoMsg(ctx context.Context, in *AgentRuleInfoMsgReq, opts ...grpc.CallOption) (*AgentRuleInfoMsgReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.GetAgentRuleInfoMsg(ctx, in, opts...)
}

// 获取当前汇率
func (m *defaultManageInnerService) GetCurrentRateInfoMsg(ctx context.Context, in *GetRateInfoMsgReq, opts ...grpc.CallOption) (*GetRateInfoMsgReply, error) {
	client := v1.NewManageInnerServiceClient(m.cli.Conn())
	return client.GetCurrentRateInfoMsg(ctx, in, opts...)
}
