// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: user.proto

package userservice

import (
	"context"

	"github.com/QuantumShiftX/farms-proto/proto-gen-go/user/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FarmsStoreInfoMsg       = v1.FarmsStoreInfoMsg
	FarmsStoreReply         = v1.FarmsStoreReply
	ForgotPasswordReq       = v1.ForgotPasswordReq
	MessageWrapper          = v1.MessageWrapper
	MsgReply                = v1.MsgReply
	MsgReq                  = v1.MsgReq
	RequestClientInfo       = v1.RequestClientInfo
	StoreInfo               = v1.StoreInfo
	UserAuthInfoMsg         = v1.UserAuthInfoMsg
	UserAuthInfoReply       = v1.UserAuthInfoReply
	UserAuthenticationReply = v1.UserAuthenticationReply
	UserAuthenticationReq   = v1.UserAuthenticationReq
	UserBalance             = v1.UserBalance
	UserEditPersonalInfoMsg = v1.UserEditPersonalInfoMsg
	UserFarmInfoMsg         = v1.UserFarmInfoMsg
	UserFarmOpsMsg          = v1.UserFarmOpsMsg
	UserFarmReply           = v1.UserFarmReply
	UserIdReq               = v1.UserIdReq
	UserLandDetail          = v1.UserLandDetail
	UserLandReply           = v1.UserLandReply
	UserLoginResp           = v1.UserLoginResp
	UserPersonalInfoMsg     = v1.UserPersonalInfoMsg
	UserPersonalInfoReply   = v1.UserPersonalInfoReply
	UserPlantingDetail      = v1.UserPlantingDetail
	UserRegisterReq         = v1.UserRegisterReq
	UserReply               = v1.UserReply
	UserReq                 = v1.UserReq
	UserSignInReq           = v1.UserSignInReq
	UserSignOutReq          = v1.UserSignOutReq
	UserStorageDetail       = v1.UserStorageDetail
	UserStorageInfoMsg      = v1.UserStorageInfoMsg
	UserStorageReply        = v1.UserStorageReply
	UserWallet              = v1.UserWallet
	VerifyAccountReq        = v1.VerifyAccountReq

	UserService interface {
		Test(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserReply, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) Test(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserReply, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}
