// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: user.proto

package userservice

import (
	"context"

	"github.com/QuantumShiftX/farms-proto/proto-gen-go/user/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ForgotPasswordReq       = v1.ForgotPasswordReq
	RequestClientInfo       = v1.RequestClientInfo
	UserAuthenticationReply = v1.UserAuthenticationReply
	UserAuthenticationReq   = v1.UserAuthenticationReq
	UserIdReq               = v1.UserIdReq
	UserLoginResp           = v1.UserLoginResp
	UserRegisterReq         = v1.UserRegisterReq
	UserReply               = v1.UserReply
	UserReq                 = v1.UserReq
	UserSignInReq           = v1.UserSignInReq
	UserSignOutReq          = v1.UserSignOutReq
	VerifyAccountReq        = v1.VerifyAccountReq

	UserService interface {
		Test(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserReply, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) Test(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserReply, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}
