// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: user.proto

package userservice

import (
	"context"

	"farms-rpc-server/app/user/pb/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserReply = v1.UserReply
	UserReq   = v1.UserReq

	UserService interface {
		Test(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserReply, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) Test(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserReply, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}
