// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.3
// source: farm/v1/farm.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FarmReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarmReq) Reset() {
	*x = FarmReq{}
	mi := &file_farm_v1_farm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmReq) ProtoMessage() {}

func (x *FarmReq) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmReq.ProtoReflect.Descriptor instead.
func (*FarmReq) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{0}
}

type FarmReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarmReply) Reset() {
	*x = FarmReply{}
	mi := &file_farm_v1_farm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarmReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmReply) ProtoMessage() {}

func (x *FarmReply) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmReply.ProtoReflect.Descriptor instead.
func (*FarmReply) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{1}
}

var File_farm_v1_farm_proto protoreflect.FileDescriptor

var file_farm_v1_farm_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x66, 0x61, 0x72, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x72, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x61, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x22, 0x09, 0x0a,
	0x07, 0x46, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x22, 0x0b, 0x0a, 0x09, 0x46, 0x61, 0x72, 0x6d,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x3d, 0x0a, 0x0b, 0x46, 0x61, 0x72, 0x6d, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x66,
	0x61, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x12,
	0x2e, 0x66, 0x61, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x32, 0x42, 0x0a, 0x10, 0x46, 0x61, 0x72, 0x6d, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x2e, 0x66, 0x61, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x72, 0x6d, 0x52,
	0x65, 0x71, 0x1a, 0x12, 0x2e, 0x66, 0x61, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x72,
	0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_farm_v1_farm_proto_rawDescOnce sync.Once
	file_farm_v1_farm_proto_rawDescData []byte
)

func file_farm_v1_farm_proto_rawDescGZIP() []byte {
	file_farm_v1_farm_proto_rawDescOnce.Do(func() {
		file_farm_v1_farm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_farm_v1_farm_proto_rawDesc), len(file_farm_v1_farm_proto_rawDesc)))
	})
	return file_farm_v1_farm_proto_rawDescData
}

var file_farm_v1_farm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_farm_v1_farm_proto_goTypes = []any{
	(*FarmReq)(nil),   // 0: farm.v1.FarmReq
	(*FarmReply)(nil), // 1: farm.v1.FarmReply
}
var file_farm_v1_farm_proto_depIdxs = []int32{
	0, // 0: farm.v1.FarmService.Test:input_type -> farm.v1.FarmReq
	0, // 1: farm.v1.FarmInnerService.Test:input_type -> farm.v1.FarmReq
	1, // 2: farm.v1.FarmService.Test:output_type -> farm.v1.FarmReply
	1, // 3: farm.v1.FarmInnerService.Test:output_type -> farm.v1.FarmReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_farm_v1_farm_proto_init() }
func file_farm_v1_farm_proto_init() {
	if File_farm_v1_farm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_farm_v1_farm_proto_rawDesc), len(file_farm_v1_farm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_farm_v1_farm_proto_goTypes,
		DependencyIndexes: file_farm_v1_farm_proto_depIdxs,
		MessageInfos:      file_farm_v1_farm_proto_msgTypes,
	}.Build()
	File_farm_v1_farm_proto = out.File
	file_farm_v1_farm_proto_goTypes = nil
	file_farm_v1_farm_proto_depIdxs = nil
}
