// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: manage.proto

package manageapiservice

import (
	"context"

	"github.com/QuantumShiftX/farms-proto/proto-gen-go/manage/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CollectionRewards    = v1.CollectionRewards
	DefaultVipInfoReply  = v1.DefaultVipInfoReply
	DepositRewards       = v1.DepositRewards
	ManageReply          = v1.ManageReply
	ManageReq            = v1.ManageReq
	RegistrationRewards  = v1.RegistrationRewards
	SendCaptchaReq       = v1.SendCaptchaReq
	SettingBaseInfoReply = v1.SettingBaseInfoReply
	SettlementConfig     = v1.SettlementConfig
	VipLevelDetail       = v1.VipLevelDetail

	ManageApiService interface {
		SendCaptcha(ctx context.Context, in *SendCaptchaReq, opts ...grpc.CallOption) (*ManageReply, error)
	}

	defaultManageApiService struct {
		cli zrpc.Client
	}
)

func NewManageApiService(cli zrpc.Client) ManageApiService {
	return &defaultManageApiService{
		cli: cli,
	}
}

func (m *defaultManageApiService) SendCaptcha(ctx context.Context, in *SendCaptchaReq, opts ...grpc.CallOption) (*ManageReply, error) {
	client := v1.NewManageApiServiceClient(m.cli.Conn())
	return client.SendCaptcha(ctx, in, opts...)
}
