// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: agent.proto

package agentservice

import (
	"context"

	"farms-rpc-server/app/agent/pb/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AgentReply = v1.AgentReply
	AgentReq   = v1.AgentReq

	AgentService interface {
		Test(ctx context.Context, in *AgentReq, opts ...grpc.CallOption) (*AgentReply, error)
	}

	defaultAgentService struct {
		cli zrpc.Client
	}
)

func NewAgentService(cli zrpc.Client) AgentService {
	return &defaultAgentService{
		cli: cli,
	}
}

func (m *defaultAgentService) Test(ctx context.Context, in *AgentReq, opts ...grpc.CallOption) (*AgentReply, error) {
	client := v1.NewAgentServiceClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}
