// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: agent/v1/agent.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AgentInnerService_GetAgentIncomeOverview_FullMethodName = "/agent.v1.AgentInnerService/GetAgentIncomeOverview"
	AgentInnerService_GetAgentDownlineStats_FullMethodName  = "/agent.v1.AgentInnerService/GetAgentDownlineStats"
	AgentInnerService_GetAgentDownlineList_FullMethodName   = "/agent.v1.AgentInnerService/GetAgentDownlineList"
	AgentInnerService_GetAgentIncomeDetails_FullMethodName  = "/agent.v1.AgentInnerService/GetAgentIncomeDetails"
)

// AgentInnerServiceClient is the client API for AgentInnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentInnerServiceClient interface {
	// 获取代理收入概览
	GetAgentIncomeOverview(ctx context.Context, in *GetAgentIncomeOverviewReq, opts ...grpc.CallOption) (*GetAgentIncomeOverviewResp, error)
	// 获取代理下线统计
	GetAgentDownlineStats(ctx context.Context, in *GetAgentDownlineStatsReq, opts ...grpc.CallOption) (*GetAgentDownlineStatsResp, error)
	// 获取代理下线列表
	GetAgentDownlineList(ctx context.Context, in *GetAgentDownlineListReq, opts ...grpc.CallOption) (*GetAgentDownlineListResp, error)
	// 获取代理收入明细
	GetAgentIncomeDetails(ctx context.Context, in *GetAgentIncomeDetailsReq, opts ...grpc.CallOption) (*GetAgentIncomeDetailsResp, error)
}

type agentInnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentInnerServiceClient(cc grpc.ClientConnInterface) AgentInnerServiceClient {
	return &agentInnerServiceClient{cc}
}

func (c *agentInnerServiceClient) GetAgentIncomeOverview(ctx context.Context, in *GetAgentIncomeOverviewReq, opts ...grpc.CallOption) (*GetAgentIncomeOverviewResp, error) {
	out := new(GetAgentIncomeOverviewResp)
	err := c.cc.Invoke(ctx, AgentInnerService_GetAgentIncomeOverview_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentInnerServiceClient) GetAgentDownlineStats(ctx context.Context, in *GetAgentDownlineStatsReq, opts ...grpc.CallOption) (*GetAgentDownlineStatsResp, error) {
	out := new(GetAgentDownlineStatsResp)
	err := c.cc.Invoke(ctx, AgentInnerService_GetAgentDownlineStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentInnerServiceClient) GetAgentDownlineList(ctx context.Context, in *GetAgentDownlineListReq, opts ...grpc.CallOption) (*GetAgentDownlineListResp, error) {
	out := new(GetAgentDownlineListResp)
	err := c.cc.Invoke(ctx, AgentInnerService_GetAgentDownlineList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentInnerServiceClient) GetAgentIncomeDetails(ctx context.Context, in *GetAgentIncomeDetailsReq, opts ...grpc.CallOption) (*GetAgentIncomeDetailsResp, error) {
	out := new(GetAgentIncomeDetailsResp)
	err := c.cc.Invoke(ctx, AgentInnerService_GetAgentIncomeDetails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentInnerServiceServer is the server API for AgentInnerService service.
// All implementations must embed UnimplementedAgentInnerServiceServer
// for forward compatibility
type AgentInnerServiceServer interface {
	// 获取代理收入概览
	GetAgentIncomeOverview(context.Context, *GetAgentIncomeOverviewReq) (*GetAgentIncomeOverviewResp, error)
	// 获取代理下线统计
	GetAgentDownlineStats(context.Context, *GetAgentDownlineStatsReq) (*GetAgentDownlineStatsResp, error)
	// 获取代理下线列表
	GetAgentDownlineList(context.Context, *GetAgentDownlineListReq) (*GetAgentDownlineListResp, error)
	// 获取代理收入明细
	GetAgentIncomeDetails(context.Context, *GetAgentIncomeDetailsReq) (*GetAgentIncomeDetailsResp, error)
	mustEmbedUnimplementedAgentInnerServiceServer()
}

// UnimplementedAgentInnerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentInnerServiceServer struct {
}

func (UnimplementedAgentInnerServiceServer) GetAgentIncomeOverview(context.Context, *GetAgentIncomeOverviewReq) (*GetAgentIncomeOverviewResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentIncomeOverview not implemented")
}
func (UnimplementedAgentInnerServiceServer) GetAgentDownlineStats(context.Context, *GetAgentDownlineStatsReq) (*GetAgentDownlineStatsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentDownlineStats not implemented")
}
func (UnimplementedAgentInnerServiceServer) GetAgentDownlineList(context.Context, *GetAgentDownlineListReq) (*GetAgentDownlineListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentDownlineList not implemented")
}
func (UnimplementedAgentInnerServiceServer) GetAgentIncomeDetails(context.Context, *GetAgentIncomeDetailsReq) (*GetAgentIncomeDetailsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentIncomeDetails not implemented")
}
func (UnimplementedAgentInnerServiceServer) mustEmbedUnimplementedAgentInnerServiceServer() {}

// UnsafeAgentInnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentInnerServiceServer will
// result in compilation errors.
type UnsafeAgentInnerServiceServer interface {
	mustEmbedUnimplementedAgentInnerServiceServer()
}

func RegisterAgentInnerServiceServer(s grpc.ServiceRegistrar, srv AgentInnerServiceServer) {
	s.RegisterService(&AgentInnerService_ServiceDesc, srv)
}

func _AgentInnerService_GetAgentIncomeOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentIncomeOverviewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentInnerServiceServer).GetAgentIncomeOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentInnerService_GetAgentIncomeOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentInnerServiceServer).GetAgentIncomeOverview(ctx, req.(*GetAgentIncomeOverviewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentInnerService_GetAgentDownlineStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentDownlineStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentInnerServiceServer).GetAgentDownlineStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentInnerService_GetAgentDownlineStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentInnerServiceServer).GetAgentDownlineStats(ctx, req.(*GetAgentDownlineStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentInnerService_GetAgentDownlineList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentDownlineListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentInnerServiceServer).GetAgentDownlineList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentInnerService_GetAgentDownlineList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentInnerServiceServer).GetAgentDownlineList(ctx, req.(*GetAgentDownlineListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentInnerService_GetAgentIncomeDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentIncomeDetailsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentInnerServiceServer).GetAgentIncomeDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentInnerService_GetAgentIncomeDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentInnerServiceServer).GetAgentIncomeDetails(ctx, req.(*GetAgentIncomeDetailsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentInnerService_ServiceDesc is the grpc.ServiceDesc for AgentInnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentInnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentInnerService",
	HandlerType: (*AgentInnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgentIncomeOverview",
			Handler:    _AgentInnerService_GetAgentIncomeOverview_Handler,
		},
		{
			MethodName: "GetAgentDownlineStats",
			Handler:    _AgentInnerService_GetAgentDownlineStats_Handler,
		},
		{
			MethodName: "GetAgentDownlineList",
			Handler:    _AgentInnerService_GetAgentDownlineList_Handler,
		},
		{
			MethodName: "GetAgentIncomeDetails",
			Handler:    _AgentInnerService_GetAgentIncomeDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/v1/agent.proto",
}
