// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: user.proto

package userinnerservice

import (
	"context"

	"github.com/QuantumShiftX/farms-proto/proto-gen-go/user/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserReply = v1.UserReply
	UserReq   = v1.UserReq

	UserInnerService interface {
		Test(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserReply, error)
	}

	defaultUserInnerService struct {
		cli zrpc.Client
	}
)

func NewUserInnerService(cli zrpc.Client) UserInnerService {
	return &defaultUserInnerService{
		cli: cli,
	}
}

func (m *defaultUserInnerService) Test(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserReply, error) {
	client := v1.NewUserInnerServiceClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}
