// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: user.proto

package userinnerservice

import (
	"context"

	"github.com/QuantumShiftX/farms-proto/proto-gen-go/user/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ForgotPasswordReq = v1.ForgotPasswordReq
	RequestClientInfo = v1.RequestClientInfo
	UserLoginReq      = v1.UserLoginReq
	UserLoginResp     = v1.UserLoginResp
	UserRegisterReq   = v1.UserRegisterReq
	UserReply         = v1.UserReply
	UserReq           = v1.UserReq
	VerifyAccountReq  = v1.VerifyAccountReq

	UserInnerService interface {
		Test(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserReply, error)
	}

	defaultUserInnerService struct {
		cli zrpc.Client
	}
)

func NewUserInnerService(cli zrpc.Client) UserInnerService {
	return &defaultUserInnerService{
		cli: cli,
	}
}

func (m *defaultUserInnerService) Test(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserReply, error) {
	client := v1.NewUserInnerServiceClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}
