// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: payment.proto

package agentpayinnerservice

import (
	"context"

	"github.com/QuantumShiftX/farms-proto/proto-gen-go/payment/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AgentPayNotifyRequest            = v1.AgentPayNotifyRequest
	AgentPayNotifyResponse           = v1.AgentPayNotifyResponse
	ApplyAgentPayRequest             = v1.ApplyAgentPayRequest
	ApplyAgentPayResponse            = v1.ApplyAgentPayResponse
	BankConfig                       = v1.BankConfig
	CommonRequest                    = v1.CommonRequest
	CreateCashierRequest             = v1.CreateCashierRequest
	CreateCashierResponse            = v1.CreateCashierResponse
	CreateOrderRequest               = v1.CreateOrderRequest
	CreateOrderResponse              = v1.CreateOrderResponse
	GetBankListInfoMsgReply          = v1.GetBankListInfoMsgReply
	GetBankListInfoMsgReq            = v1.GetBankListInfoMsgReq
	GetPaymentConfListMsgReply       = v1.GetPaymentConfListMsgReply
	GetPaymentConfListMsgReq         = v1.GetPaymentConfListMsgReq
	GetPendingOrderMsgReply          = v1.GetPendingOrderMsgReply
	GetPendingOrderMsgReq            = v1.GetPendingOrderMsgReq
	OrderInfo                        = v1.OrderInfo
	PayNotifyData                    = v1.PayNotifyData
	PayNotifyResponse                = v1.PayNotifyResponse
	PayParams                        = v1.PayParams
	PaymentConfInfo                  = v1.PaymentConfInfo
	PaymentNotificationReq           = v1.PaymentNotificationReq
	PaymentReply                     = v1.PaymentReply
	PaymentReq                       = v1.PaymentReq
	QueryAgentPayBalanceRequest      = v1.QueryAgentPayBalanceRequest
	QueryAgentPayBalanceResponse     = v1.QueryAgentPayBalanceResponse
	QueryAgentPayCertificateRequest  = v1.QueryAgentPayCertificateRequest
	QueryAgentPayCertificateResponse = v1.QueryAgentPayCertificateResponse
	QueryAgentPayOrderRequest        = v1.QueryAgentPayOrderRequest
	QueryAgentPayOrderResponse       = v1.QueryAgentPayOrderResponse
	QueryOrderByUTRRequest           = v1.QueryOrderByUTRRequest
	QueryOrderRequest                = v1.QueryOrderRequest
	QueryOrderResponse               = v1.QueryOrderResponse
	RechargeChannel                  = v1.RechargeChannel
	RechargeChannelsInfoMsgReply     = v1.RechargeChannelsInfoMsgReply
	RechargeChannelsInfoMsgReq       = v1.RechargeChannelsInfoMsgReq
	RechargeInfo                     = v1.RechargeInfo
	TransactionRecord                = v1.TransactionRecord
	UserRechargeConfirmMsgReply      = v1.UserRechargeConfirmMsgReply
	UserRechargeConfirmMsgReq        = v1.UserRechargeConfirmMsgReq
	UserRechargeInfoMsgReply         = v1.UserRechargeInfoMsgReply
	UserRechargeInfoMsgReq           = v1.UserRechargeInfoMsgReq
	UserSetWithdrawChannelMsgReply   = v1.UserSetWithdrawChannelMsgReply
	UserSetWithdrawChannelMsgReq     = v1.UserSetWithdrawChannelMsgReq
	UserTransactionRecordsMsgReply   = v1.UserTransactionRecordsMsgReply
	UserTransactionRecordsMsgReq     = v1.UserTransactionRecordsMsgReq
	UserWithdrawAccountInfoMsgReply  = v1.UserWithdrawAccountInfoMsgReply
	UserWithdrawAccountInfoMsgReq    = v1.UserWithdrawAccountInfoMsgReq
	UserWithdrawInfoMsgReply         = v1.UserWithdrawInfoMsgReply
	UserWithdrawInfoMsgReq           = v1.UserWithdrawInfoMsgReq
	WithdrawAccount                  = v1.WithdrawAccount
	WithdrawChannel                  = v1.WithdrawChannel
	WithdrawInfo                     = v1.WithdrawInfo

	AgentPayInnerService interface {
		// 申请代付
		ApplyAgentPay(ctx context.Context, in *ApplyAgentPayRequest, opts ...grpc.CallOption) (*ApplyAgentPayResponse, error)
		// 查询代付订单
		QueryAgentPayOrder(ctx context.Context, in *QueryAgentPayOrderRequest, opts ...grpc.CallOption) (*QueryAgentPayOrderResponse, error)
		// 查询代付凭证
		QueryAgentPayCertificate(ctx context.Context, in *QueryAgentPayCertificateRequest, opts ...grpc.CallOption) (*QueryAgentPayCertificateResponse, error)
		// 查询余额
		QueryAgentPayBalance(ctx context.Context, in *QueryAgentPayBalanceRequest, opts ...grpc.CallOption) (*QueryAgentPayBalanceResponse, error)
		// 验证回调通知(内部使用)
		HandleAgentPayNotify(ctx context.Context, in *AgentPayNotifyRequest, opts ...grpc.CallOption) (*AgentPayNotifyResponse, error)
	}

	defaultAgentPayInnerService struct {
		cli zrpc.Client
	}
)

func NewAgentPayInnerService(cli zrpc.Client) AgentPayInnerService {
	return &defaultAgentPayInnerService{
		cli: cli,
	}
}

// 申请代付
func (m *defaultAgentPayInnerService) ApplyAgentPay(ctx context.Context, in *ApplyAgentPayRequest, opts ...grpc.CallOption) (*ApplyAgentPayResponse, error) {
	client := v1.NewAgentPayInnerServiceClient(m.cli.Conn())
	return client.ApplyAgentPay(ctx, in, opts...)
}

// 查询代付订单
func (m *defaultAgentPayInnerService) QueryAgentPayOrder(ctx context.Context, in *QueryAgentPayOrderRequest, opts ...grpc.CallOption) (*QueryAgentPayOrderResponse, error) {
	client := v1.NewAgentPayInnerServiceClient(m.cli.Conn())
	return client.QueryAgentPayOrder(ctx, in, opts...)
}

// 查询代付凭证
func (m *defaultAgentPayInnerService) QueryAgentPayCertificate(ctx context.Context, in *QueryAgentPayCertificateRequest, opts ...grpc.CallOption) (*QueryAgentPayCertificateResponse, error) {
	client := v1.NewAgentPayInnerServiceClient(m.cli.Conn())
	return client.QueryAgentPayCertificate(ctx, in, opts...)
}

// 查询余额
func (m *defaultAgentPayInnerService) QueryAgentPayBalance(ctx context.Context, in *QueryAgentPayBalanceRequest, opts ...grpc.CallOption) (*QueryAgentPayBalanceResponse, error) {
	client := v1.NewAgentPayInnerServiceClient(m.cli.Conn())
	return client.QueryAgentPayBalance(ctx, in, opts...)
}

// 验证回调通知(内部使用)
func (m *defaultAgentPayInnerService) HandleAgentPayNotify(ctx context.Context, in *AgentPayNotifyRequest, opts ...grpc.CallOption) (*AgentPayNotifyResponse, error) {
	client := v1.NewAgentPayInnerServiceClient(m.cli.Conn())
	return client.HandleAgentPayNotify(ctx, in, opts...)
}
