// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: user.proto

package userrpcinnerservice

import (
	"context"

	"github.com/QuantumShiftX/farms-proto/proto-gen-go/user/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdjustHarvestTimeRequest      = v1.AdjustHarvestTimeRequest
	AdjustHarvestTimeResponse     = v1.AdjustHarvestTimeResponse
	AllUserRankingInfoMsgData     = v1.AllUserRankingInfoMsgData
	AllUserRankingInfoMsgReply    = v1.AllUserRankingInfoMsgReply
	AllUserRankingInfoMsgReq      = v1.AllUserRankingInfoMsgReq
	CheckCropsNeedsRequest        = v1.CheckCropsNeedsRequest
	CheckCropsNeedsResponse       = v1.CheckCropsNeedsResponse
	ForgotPasswordReq             = v1.ForgotPasswordReq
	FriendRankingInfo             = v1.FriendRankingInfo
	GetOnlineUserListReply        = v1.GetOnlineUserListReply
	GetOnlineUserListReq          = v1.GetOnlineUserListReq
	GrowthProgressRequest         = v1.GrowthProgressRequest
	GrowthProgressResponse        = v1.GrowthProgressResponse
	LookUserFarmsInfoMsgData      = v1.LookUserFarmsInfoMsgData
	LookUserFarmsInfoMsgReply     = v1.LookUserFarmsInfoMsgReply
	LookUserFarmsInfoMsgReq       = v1.LookUserFarmsInfoMsgReq
	MaintenanceNeeds              = v1.MaintenanceNeeds
	MaintenanceNeedsRequest       = v1.MaintenanceNeedsRequest
	MaintenanceNeedsResponse      = v1.MaintenanceNeedsResponse
	MsgData                       = v1.MsgData
	MsgReply                      = v1.MsgReply
	MsgReq                        = v1.MsgReq
	MyRankingInfo                 = v1.MyRankingInfo
	PlantInfo                     = v1.PlantInfo
	PlantStateInfo                = v1.PlantStateInfo
	PlantStateRequest             = v1.PlantStateRequest
	PlantStateResponse            = v1.PlantStateResponse
	PlantStatusRequest            = v1.PlantStatusRequest
	PlantStatusResponse           = v1.PlantStatusResponse
	RequestClientInfo             = v1.RequestClientInfo
	StageTime                     = v1.StageTime
	StageTimelinesRequest         = v1.StageTimelinesRequest
	StageTimelinesResponse        = v1.StageTimelinesResponse
	TimeReductionRequest          = v1.TimeReductionRequest
	TimeReductionResponse         = v1.TimeReductionResponse
	UserAuthInfoMsgData           = v1.UserAuthInfoMsgData
	UserAuthInfoMsgReply          = v1.UserAuthInfoMsgReply
	UserAuthInfoMsgReq            = v1.UserAuthInfoMsgReq
	UserAuthenticationReply       = v1.UserAuthenticationReply
	UserAuthenticationReq         = v1.UserAuthenticationReq
	UserBalance                   = v1.UserBalance
	UserEditPersonalInfoMsgReply  = v1.UserEditPersonalInfoMsgReply
	UserEditPersonalInfoMsgReq    = v1.UserEditPersonalInfoMsgReq
	UserEditSensitiveInfoMsgReply = v1.UserEditSensitiveInfoMsgReply
	UserEditSensitiveInfoMsgReq   = v1.UserEditSensitiveInfoMsgReq
	UserFarmInfoMsgData           = v1.UserFarmInfoMsgData
	UserFarmInfoMsgReply          = v1.UserFarmInfoMsgReply
	UserFarmInfoMsgReq            = v1.UserFarmInfoMsgReq
	UserFarmOpsMsgReply           = v1.UserFarmOpsMsgReply
	UserFarmOpsMsgReq             = v1.UserFarmOpsMsgReq
	UserFortuneTreeInfo           = v1.UserFortuneTreeInfo
	UserFortuneTreeInfoMsgData    = v1.UserFortuneTreeInfoMsgData
	UserFortuneTreeInfoMsgReply   = v1.UserFortuneTreeInfoMsgReply
	UserFortuneTreeInfoMsgReq     = v1.UserFortuneTreeInfoMsgReq
	UserFriendRankingInfoMsgData  = v1.UserFriendRankingInfoMsgData
	UserFriendRankingInfoMsgReply = v1.UserFriendRankingInfoMsgReply
	UserFriendRankingInfoMsgReq   = v1.UserFriendRankingInfoMsgReq
	UserIdReq                     = v1.UserIdReq
	UserLandDetail                = v1.UserLandDetail
	UserLandInfoMsgData           = v1.UserLandInfoMsgData
	UserLandInfoMsgReply          = v1.UserLandInfoMsgReply
	UserLandInfoMsgReq            = v1.UserLandInfoMsgReq
	UserLoginResp                 = v1.UserLoginResp
	UserPersonalInfoMsgData       = v1.UserPersonalInfoMsgData
	UserPersonalInfoMsgReply      = v1.UserPersonalInfoMsgReply
	UserPersonalInfoMsgReq        = v1.UserPersonalInfoMsgReq
	UserPlantingDetail            = v1.UserPlantingDetail
	UserPurchaseGoodsMsgReply     = v1.UserPurchaseGoodsMsgReply
	UserPurchaseGoodsMsgReq       = v1.UserPurchaseGoodsMsgReq
	UserRegisterReq               = v1.UserRegisterReq
	UserReply                     = v1.UserReply
	UserReq                       = v1.UserReq
	UserSignInReq                 = v1.UserSignInReq
	UserSignOutReq                = v1.UserSignOutReq
	UserStorageDetail             = v1.UserStorageDetail
	UserStorageInfoMsgData        = v1.UserStorageInfoMsgData
	UserStorageInfoMsgReply       = v1.UserStorageInfoMsgReply
	UserStorageInfoMsgReq         = v1.UserStorageInfoMsgReq
	UserWallet                    = v1.UserWallet
	VerifyAccountReq              = v1.VerifyAccountReq

	UserRpcInnerService interface {
		// 获取在线用户ID信息
		GetOnlineUserList(ctx context.Context, in *GetOnlineUserListReq, opts ...grpc.CallOption) (*GetOnlineUserListReply, error)
	}

	defaultUserRpcInnerService struct {
		cli zrpc.Client
	}
)

func NewUserRpcInnerService(cli zrpc.Client) UserRpcInnerService {
	return &defaultUserRpcInnerService{
		cli: cli,
	}
}

// 获取在线用户ID信息
func (m *defaultUserRpcInnerService) GetOnlineUserList(ctx context.Context, in *GetOnlineUserListReq, opts ...grpc.CallOption) (*GetOnlineUserListReply, error) {
	client := v1.NewUserRpcInnerServiceClient(m.cli.Conn())
	return client.GetOnlineUserList(ctx, in, opts...)
}
